import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import type { Metadata } from "next";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const cadtMonoDisplay = localFont({
  src: "../../public/fonts/CADTMonoDisplay-Regular.ttf",
});

export const Niradei = localFont({
  src: [
    {
      path: "../../public/fonts/Niradei-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Niradei-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-niradei",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
